version: "3"

tasks: 
  generate: 
    aliases: 
      - gen 
    desc: "aaaa"
    cmds:
      - protoc HelloChat.proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
